/** Enum of all possible action types. */
export enum Action {
    REQUEST_LOGIN,
    RECEIVE_LOGIN,
    FAILURE_LOGIN,
    CLEAR_ERROR_LOGIN,

    REQUEST_ARTICLE_LIST,
    SUCCESS_ARTICLE_LIST,
    FAILURE_ARTICLE_LIST,

    LOAD_ARTICLE,
    SUCCESS_SAVE_ARTICLE,
    FAILURE_SAVE_ARTICLE,
    UPDATE_ARTICLE,
    REQUEST_ARTICLE_DELETE,
    SUCCESS_ARTICLE_DELETE
}
